In [2]:
import pandas as pd

In [3]:
s = pd.Series([1, 2, 3, 4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
data = [[1, 444, 'abc'],
        [2, 555, 'def'],
        [3, 666, 'ghi'],
        [4, 444, 'xyz']]

df = pd.DataFrame(data, columns=['idx', 'std_id', 'depar'])
df

   idx  std_id depar
0    1     444   abc
1    2     555   def
2    3     666   ghi
3    4     444   xyz

In [10]:
data = {'idx' : [1, 2, 3, 4],
        'std_id' : [444, 555, 666, 444],
        'depart' : ['abc', 'def', 'ghi', 'xyz']
        }
df = pd.DataFrame(data)
df

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [13]:

colums = ['idx-1', 'std_id1', 'dep']
idx = ['a', 'b', 'c', 'd']
df.index = idx
df.columns = colums
display(df)

   idx-1  std_id1  dep
a      1      444  abc
b      2      555  def
c      3      666  ghi
d      4      444  xyz

In [14]:
df

   idx-1  std_id1  dep
a      1      444  abc
b      2      555  def
c      3      666  ghi
d      4      444  xyz

In [19]:
# df.dtypes
df['idx-1'].dtype

dtype('int64')

In [20]:
df['std_id1'] = df['std_id1'].astype('category')
df.dtypes

idx-1         int64
std_id1    category
dep             str
dtype: object

In [21]:
cols = ['idx-1', 'dep']
df[cols] = df[cols].astype('category')

In [22]:
df.dtypes

idx-1      category
std_id1    category
dep        category
dtype: object

In [23]:
data = {'idx' : [1, 2, 3, 4],
        'std_id' : [444, 555, 666, 444],
        'depart' : ['abc', 'def', 'ghi', 'xyz']
        }

df = pd.DataFrame(data)
df

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [24]:
df.head()

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [26]:
df.tail(1)

   idx  std_id depart
3    4     444    xyz

In [30]:
df['depart'] = df['depart'].astype('category')
df.dtypes

idx          int64
std_id       int64
depart    category
dtype: object

In [31]:
df.describe(include='category')

       depart
count       4
unique      4
top       abc
freq        1

In [32]:
df.describe()

            idx      std_id
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [34]:
df.columns

Index(['idx', 'std_id', 'depart'], dtype='str')

In [36]:
df['std_id'].unique()
df['std_id'].nunique()

3

In [38]:
df['std_id'].idxmin()
df['std_id'].idxmax()

2

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idx     4 non-null      int64
 1   std_id  4 non-null      int64
 2   depart  4 non-null      category
dtypes: category(1), int64(2)
memory usage: 404.0 bytes

In [41]:
d = df['std_id'].value_counts()
d

std_id
444    2
555    1
666    1
Name: count, dtype: int64

In [43]:
x = df.values
type(x)

numpy.ndarray

In [ ]:
df1 =df.replace(555, 'fahd', inplace = True)
df1

   idx std_id depart
0    1    444    abc
1    2   fahd    def
2    3    666    ghi
3    4    444    xyz

In [48]:
df

   idx std_id depart
0    1    444    abc
1    2   fahd    def
2    3    666    ghi
3    4    444    xyz

In [51]:
df.std_id = df.std_id.map({444:6564, 555:65488})

In [52]:
df

   idx  std_id  depart
0    1  6564.0     NaN
1    2     NaN     NaN
2    3     NaN     NaN
3    4  6564.0     NaN

In [53]:
data = {'idx' : [1, 2, 3, 4],
        'std_id' : [444, 555, 666, 444],
        'depart' : ['abc', 'def', 'ghi', 'xyz']
        }

df = pd.DataFrame(data)
df

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [55]:
df.iloc[2,1]

np.int64(666)

In [56]:
df.iloc[:]

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [62]:
x = df.iloc[: , : 2]
y = df.iloc[ : , -1]
x

   idx  std_id
0    1     444
1    2     555
2    3     666
3    4     444